---
- name: Packer Demo with Ansible Provisioner
  hosts: all
  vars_files: 
    - packages.yaml
  tasks:
  - name: Update the yum repository
    yum:
      update_cache: yes
  - name: Dependencies installation
    yum:
      name: "{{ item }}"
      state: present
    loop: "{{ packages }}"
